config/routes.rb
Rails.application.routes.draw do
  root "tasks#index"
  resources :users, only: [:new, :create, :show ]
  namespace :admin do
    resources :users
  end
  resources :sessions, only: [:new, :create, :edit, :destroy]
  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/label.rb
class Label < ApplicationRecord
  has_many :task_labels, dependent: :destroy
  has_many :tasks, through: :task_labels
end

app/models/task.rb
class Task < ApplicationRecord
  validates :name, presence: true
  validates :content, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
  validates :priority, presence: true
  validate :date_cannot_be_in_the_past

  belongs_to :user

  has_many :task_labels, dependent: :destroy
  has_many :labels, through: :task_labels

  enum priority: { 低: 0, 中: 1, 高: 2 }

  def date_cannot_be_in_the_past
    if deadline < Date.today - 1
      errors.add(:deadline, "過去の日付は設定できません。")
    end
  end

  scope :search, -> (search_params) do
    name = search_params[:name]
    status = search_params[:status]
    label = search_params[:label_id]
    return if search_params.blank?
    name_like(name).check_status(status).check_label(label)
  end

  scope :name_like, -> name { where('name LIKE ?', "%#{name}%") if name.present? }
  scope :check_status, -> status { where(status: status) if status.present? }
  scope :deadline, -> { order(deadline: :desc) }
  scope :default, -> { order(created_at: :desc) }
  scope :priority, -> { order(priority: :desc) }
  scope :check_label, -> label_id { joins(:labels).where(labels: { id: label_id }) if label_id.present? }
end

app/models/task_label.rb
class TaskLabel < ApplicationRecord
  belongs_to :task
  belongs_to :label
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length:{ maximum: 30 }
  validates :email, presence: true, length:{ maximum: 255 },
  format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  before_validation { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  has_many :tasks, dependent: :destroy

  before_destroy :ensure_admin_deatroy
  before_update :ensure_admin_update

  private

  def ensure_admin_deatroy
    throw(:abort) if User.where(admin: true).count <= 1 && self.admin == true
  end

  def ensure_admin_update
    if User.where(admin: true).count == 1 && self.admin == false
      errors.add(:admin,"は、最低でも１人は必要です。")
      throw(:abort)
    end
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update, :destroy, :show]
  before_action :require_admin

  PREVIEW = 5

  def index
    @users = User.select(:id, :name, :email, :admin).order(created_at: :asc).page(params[:page]).per(PREVIEW)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_user_path(@user.id), notice:"ユーザー「#{@user.name}」を登録しました"
    else
      render :new
    end
  end
  
  def edit
  end

  def update
    if @user.update(user_params)
      flash[:success] = "#{@user.name}の登録内容を更新しました。"
      redirect_to admin_user_path(@user)
    else
      flash.now[:danger] = "更新できませんでした。"
      render :edit
    end
  end  

  def show
    @tasks = @user.tasks
    @tasks = @tasks.page(params[:page]).per(PREVIEW)
  end

  def destroy
    if @user.destroy
      flash[:info] = "#{@user.name}さんのデータを削除しました"
      redirect_to admin_users_path
    else
      flash[:info] = '管理権限ユーザーは、最低でも１人は必要です。'
      redirect_to admin_users_path
    end
  end
  

  private
  def user_params
    params.require(:user).permit(
      :name,
      :email,
      :password,
      :password_confirmation,
      :admin)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def require_admin
    unless current_user.admin?
      flash[:warning] = "管理者以外はアクセスできません。"
      redirect_to tasks_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :basic_auth
  add_flash_types :success, :info, :warning, :danger

  protect_from_forgery with: :exception
  include SessionsHelper

  def authenticate_user
    if current_user == nil
      flash[:notice] = "ログインが必要です。"
      redirect_to new_session_path
    end
  end

  # def basic_auth
  #   authenticate_or_request_with_http_basic do |username, password|
  #     username == 'test' && password == '1234'
  #   end
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, {only: [:edit, :destroy]}

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      flash[:success] = 'ログインしました'
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash.now[:warning] = "ログインに失敗しました。"
      render :new
    end
  end
  
  def destroy
    session.delete(:user_id)
    flash[:info] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user
  before_action :set_task, only: [:edit, :update, :show, :destroy]
  
  PREVIEW = 5
  
  def index    
    @get_params = task_get_params
    @tasks = Task.search(@get_params)
    if params[:sort_expired]
      @tasks = @tasks.deadline
    elsif params[:sort_priority]
      @tasks = @tasks.priority
    else
      @tasks = @tasks.default
    end
    @tasks = @tasks.page(params[:page]).per(PREVIEW)
  end

  def new
    @task = Task.new
    @task.deadline = Date.today
  end

  def create
    @task = current_user.tasks.build(task_params)
    if @task.save
      redirect_to tasks_path, success: "新しいToDoリストを登録しました！"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, info: "#{@task.name}を更新しました。"
    else
      flash[:danger] = "更新に失敗しました。"
      render :edit
    end
  end  

  def show
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, danger: "#{@task.name}を削除しました。"
  end

  private  
  def task_params
    params.require(:task).permit(
      :name,
      :content,
      :deadline,
      :priority,
      :status,
      label_ids:[]
    )    
  end

  def set_task
    @task = Task.find(params[:id])    
  end

  def task_get_params
    params.fetch(:search, {}).permit(:name, :status, :label_id )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user, only: [:show]

  PEREVIEW = 10

  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to user_path(@user.id)
      session[:user_id] = @user.id
    else
      render :new
    end
  end

  def show
    @user = current_user
    @tasks = @user.tasks&.page(params[:page]).per(PEREVIEW)
    redirect_to tasks_path if @user.id != params[:id].to_i
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email, :password,
                                :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])    
  end

  def logged_in?
    current_user.present?
  end  
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/users/edit.html.erb
<h2>管理者用アカウント編集</h2>
<div class="container">
  <div class= "row">
<%= form_with(model: [:admin,@user], local: true) do |f| %>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :アカウント名 %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :メールアドレス %><br>
    <%= f.email_field :email, class:"form-control" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.label :管理権限付与 %>
    <%= f.check_box :admin %>
  </div>
  <br>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= f.submit "登録", class:"btn btn-primary btn-block" %>
  </div>
  <div class="form-group col-xs-6 col-xs-offset-3">
    <%= link_to "ユーザーリストに戻る", admin_users_path, class: "btn btn-default btn-block" %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<h1>ユーザーリスト</h1>
<br>
<button type="button" class="btn btn-info"><%= link_to 'ユーザー新規作成', new_admin_user_path %></button>
<br>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>ユーザー名</th>
      <th>メールアドレス</th>
      <th>タスク数</th>
      <th>ユーザー管理権限</th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= link_to user.name, admin_user_path(user.id) %></td>
        <td><%= user.email %></td>
        <td><%= user.tasks.count %></td>
        <td><%= user.admin? ? "有り": "無し" %></td>
        <td><button type="button" class="btn btn-success"><%= link_to '編集', edit_admin_user_path(user) %></button></td>
        <td><button type="button" class="btn btn-warning"><%= link_to '削除', admin_user_path(user), method: :delete, id: "delete_button", data: { confirm: "本当に#{user.name}さんを削除しても良いですか?" } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/users/new.html.erb
  <div class="contentBx">
    <div class="formBx">
      <h2>管理者用アカウント新規登録</h2>
      <%= form_with(model: [:admin,@user], local: true) do |f| %>
        <div class="inputBx">
          <span class="label"><%= f.label :アカウント名　%></span>
          <%= f.text_field :name %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :メールアドレス　%></span>
          <%= f.email_field :email %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :パスワード（半角英数字６文字以上）　%></span>
          <%= f.password_field :password %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :パスワード（確認用）%></span>
          <%= f.password_field :password_confirmation %>
        </div>
          <div class="inputBx">
            <span class="label"><%= f.label :管理権限付与 %></span>
            <%= f.check_box :admin %>
          </div><br>
        <div class="inputBx">
          <%= f.submit "新規作成", disable_with: '新規作成...' %>
        </div>        
      <% end %>
      アカウントをお持ちですか？　<%= link_to "ログインする", new_session_path %>
    </div>
  </div>

app/views/admin/users/show.html.erb
<div class="container">
  <div class = "row">
    <h1><%= @user.name%>さんページ</h1>
    
  <div class="show_user_name  clearfix">
    <%= link_to "ユーザーリストに戻る", admin_users_path %><br>
    <%= link_to "アカウント編集", edit_admin_user_path %><br>
    <%= link_to 'アカウント削除', admin_user_path(@user), method: :delete, data: { confirm: "本当に#{@user.name}さんを削除しても良いですか?" } %>
  </div>
  </div>
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th>ID</th>
        <td><%= @user.id %></td>
      </tr>
      <tr>
        <th>ユーザー名</th>
        <td><%= @user.name%></td>
      </tr>
      <tr>
        <th>メールアドレス</th>
        <td><%= @user.email %></td>
      </tr>
      <tr>
        <th>タスク数</th>
        <td><%= @user.tasks.count %></td>
      </tr>
      <tr>
        <th>ユーザー管理権限</th>
        <td><%= @user.admin? ? "有り":"無し" %></td>
      </tr>
    </thead>
  </table>
  </div>
  <br>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>タスク名</th>
        <th>内容</th>
        <th>終了期限</th>
        <th>ステータス</th>
        <th>優先順位</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.name %></td>
          <td><%= task.content.truncate(20) %></td>
          <td><%= task.deadline %></td>
          <td><%= task.status %></td>
          <td><%= task.priority %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @tasks %>
</div>

app/views/layouts/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-inverse">
  <% if logged_in? %>
    <div class="container-fluid container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="navbar-brand">
          <%= link_to 'ToDo LIST', tasks_path, style:"color: #fff; text-decoration: none;" %>
        </div>
      </div>
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav navbar-right">          
          <li><%= link_to 'ホームに戻る', tasks_path %></li>      
          <li><%= link_to "プロフィール", user_path(current_user.id) %></li>
          <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete %></li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="navbar-brand">
      <%= link_to 'TODO LIST', new_user_path, style:"color: #fff; text-decoration: none;" %>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoListRails</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render '/layouts/nav' %>
    <%= render '/layouts/flash_message'%>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<div class="container">
  <div class= "row">
    <div class="col-xs-8 col-xs-offset-2">
      <%= form_with(model: @task, local:true) do |f| %>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.label :タスク名 %><br>
          <%= f.text_field :name, class: "form-control" %>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.label :内容 %><br>
          <%= f.text_area :content, rows: "6", class: "form-control" %>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.label :終了期限 %><br>
          <%= f.date_field :deadline %>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.label :優先順位 %><br>
          <%= f.select(:priority, options_for_select(["低", "中", "高"]),   {include_blank: '選択して下さい'}, {class: "selectpicker select-option"}) %>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.label :ステータス %><br>
          <%= f.select(:status, options_for_select( ["未着手", "着手中", "完了"]),   {include_blank: '選択して下さい'}, {class: "selectpicker select-option"}) %>
        </div>
        <div class="form-check col-xs-8 col-xs-offset-2">
          <div class="form-check-input"><%= f.collection_check_boxes(:label_ids, Label.all, :id, :name) %></div>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= f.submit "登録", disable_with: '登録中...', class: "btn btn-info btn-block" %>
        </div>
        <div class="form-group col-xs-8 col-xs-offset-2">
          <%= link_to '一覧に戻る', tasks_path, class: "btn btn-default btn-block" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/tasks/edit.html.erb
<h2>ToDoリストを編集する</h2>
<%= render 'form' %>

app/views/tasks/index.html.erb
<div class="table">
  <div>
    <%= form_with(scope: :search, url: tasks_path, method: :get, local: true) do |f| %>
      <%= f.label :タスク検索 %>
      <%= f.text_field :name, placeholder: "キーワード検索", value: @get_params[:title] %>
      <%= f.label :ステータス %>
      <%= f.select(:status, options_for_select([ "未着手", "着手中", "完了" ]),{include_blank: '未選択'}, {class: "selectpicker select-option "}) %>
      <%= f.label :ラベル %>
      <%= f.select("label_id", Label.pluck(:name, :id), {include_blank: '未選択'},{class: "selectpicker select-option"}) %>
      <%# <%= f.select("label_id", Label.pluck(:name, :id), { include_blank: true }) %>
      <%= f.submit "検索" %>
      <%= link_to "検索条件クリア", tasks_path %>
    <% end %>
  </div><br>

  <button type="button"><%= link_to "新しいToDoリストを作成する", new_task_path %></button>
  <table class="table table-hover">
    <thead>
      <tr>
        <th>作成者</th>
        <th>タスク名</th>
        <th>内容</th>
        <th>期限 <%= link_to tasks_path(sort_expired: "true"), class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true" style="font-size: 15px;"></span>
        <% end %></th>
        <th>優先度 <%= link_to tasks_path(sort_priority: "true"),  class: 'btn btn-default' do %>
        <span class="glyphicon glyphicon-sort-by-attributes-alt" aria-hidden="true" style="font-size: 15px;"></span>
        <% end %></th>
        <th>ステータス</th>
        <th>ラベル</th>
      </tr>
    </thead>
    <tbody>
      <% @tasks.each do |task| %>
        <tr>
          <td><%= task.user.name %></td>
          <td><%= task.name %></td>
          <td><%= task.content.truncate(25) %></td>
          <td><%= task.deadline %></td>
          <td><%= task.priority %></td>
          <td><%= task.status %></td>
          <td>
            <% task.labels.each do |label| %>
              <%= label.name %>
            <% end %>
          </td>
          <td><button type="button"><%= link_to "詳細", task_path(task.id), class: "btn btn-default" %></button></td>
          <% if task.user.id == current_user.id %>
            <td><button type="button"><%= link_to "編集", edit_task_path(task.id), class: "btn btn-default" %></button></td>
            <td><button type="button"><%= link_to "削除", task_path(task.id), method: :delete, data: { confirm: '本当に削除していいですか?' }, class: "btn btn-default" %></button></td>              
          <% end %>
          </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @tasks %>
</div>

app/views/tasks/new.html.erb
<h2>新しいToDoリストを作成する</h2>
<%= render "form" %>

app/views/tasks/show.html.erb
<p>タスク名: <%= @task.name %></p>
<p>詳細: <%= @task.content %></p>
<%= link_to '編集', edit_task_path%> | <%= link_to '戻る', tasks_path %>

app/views/users/new.html.erb
  <div class="contentBx">
    <div class="formBx">
      <h2>アカウント新規登録</h2>
      <%= form_with(model: @user, local: true) do |f| %>
        <div class="inputBx">
          <span class="label"><%= f.label :アカウント名　%></span>
          <%= f.text_field :name %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :メールアドレス　%></span>
          <%= f.email_field :email %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :パスワード（半角英数字６文字以上）　%></span>
          <%= f.password_field :password %>
        </div>
        <div class="inputBx">
          <span class="label"><%= f.label :パスワード（確認用）%></span>
          <%= f.password_field :password_confirmation %>
        </div><br>
        <div class="inputBx">
          <%= f.submit "新規作成", disable_with: '新規作成...' %>
        </div>        
      <% end %>
      アカウントをお持ちですか？　<%= link_to "ログインする", new_session_path %>
    </div>
  </div>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>
<p><%= @user.email %></p>
<br>
<% if current_user.admin? %>
  <%= link_to "管理者画面", admin_users_path %>
<% end %>
<br>
<button type="button" class="btn btn-info"><%= link_to '新規作成', new_task_path %></button>
<br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>タスク名</th>
      <th>概要</th>
      <th>終了期限</th>
      <th>ステータス</th>
      <th>優先順位</th>
      <th>ラベル</th>
    </tr>
  </thead>
  <tbody>
    <% @tasks.each do |t| %>
      <tr>
        <td><%= link_to t.name ,task_path(t.id) %></td>
        <td><%= t.content.truncate(20) %></td>
        <td><%= t.deadline %></td>
        <td><%= t.status %></td>
        <td><%= t.priority %></td>
        <td>
          <% t.labels.each do |label| %>
            <%= label.name %>
          <% end %>
          </td>
        <td><button type="button"><%= link_to "編集", edit_task_path(t.id) %></button></td>
        <td><button type="button"><%= link_to "削除", task_path(t.id), method: :delete, data: { confirm: '本当に削除していいですか?' } %></button></td>              
      </tr>
    <% end %>
  </tbody>
</table>
<div class="paginate">
  <%= paginate @tasks %>
</div>